{
 "title": "ActiveMQ",
 "tags": [ "telegraf" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "activemq_OperatingSystem_ProcessCpuLoad",
     "legendFormat": "{{jolokia_agent_url}}-ProcessCpuLoad"
    },
    {
     "expr": "activemq_OperatingSystem_SystemCpuLoad",
     "legendFormat": "{{jolokia_agent_url}}-SystemCpuLoad"
    },
    {
     "expr": "activemq_OperatingSystem_SystemLoadAverage",
     "legendFormat": "{{jolokia_agent_url}}-SystemLoadAverage"
    }
   ]
  },
  {
   "title": "Java Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "activemq_jvm_memory_HeapMemoryUsage_max",
     "legendFormat": "HeapMemoryUsage_max"
    },
    {
     "expr": "activemq_jvm_memory_HeapMemoryUsage_used",
     "legendFormat": "HeapMemoryUsage_used"
    }
   ]
  },
  {
   "title": "Total Consumer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "activemq_broker_TotalConsumerCount",
     "legendFormat": "{{jolokia_agent_url}}-TotalConsumerCount"
    }
   ]
  },
  {
   "title": "Total Dequeue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "activemq_broker_TotalDequeueCount",
     "legendFormat": "{{jolokia_agent_url}}-TotalDequeueCount"
    }
   ]
  },
  {
   "title": "Total Message",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "activemq_broker_TotalMessageCount",
     "legendFormat": "{{jolokia_agent_url}}-TotalMessageCount"
    }
   ]
  },
  {
   "title": "Total Enqueue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "activemq_broker_TotalEnqueueCount",
     "legendFormat": "{{jolokia_agent_url}}-TotalEnqueueCount"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pool Collection",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": "activemq_jvm_memory_pool_CollectionUsage_max",
       "legendFormat": "{{pool_name}}-MAX"
      },
      {
       "expr": "activemq_jvm_memory_pool_CollectionUsage_used",
       "legendFormat": "{{pool_name}}-Used"
      }
     ]
    },
    {
     "title": "Memory Pool Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": "activemq_jvm_memory_pool_Usage_max",
       "legendFormat": "{{pool_name}}-MAX"
      },
      {
       "expr": "activemq_jvm_memory_pool_Usage_used",
       "legendFormat": "{{pool_name}}-Used"
      }
     ]
    },
    {
     "title": "Memory Pool PeakUsage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 15, "y": 17 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": "activemq_jvm_memory_pool_PeakUsage_max",
       "legendFormat": "{{pool_name}}-MAX"
      },
      {
       "expr": "activemq_jvm_memory_pool_PeakUsage_used",
       "legendFormat": "{{pool_name}}-Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Broker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker Store",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "activemq_broker_StoreLimit",
       "legendFormat": "{{jolokia_agent_url}}-StoreLimit"
      },
      {
       "expr": "activemq_broker_StorePercentUsage",
       "legendFormat": "{{jolokia_agent_url}}-StorePercentUsage"
      }
     ]
    },
    {
     "title": "Broker Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "activemq_broker_MemoryLimit",
       "legendFormat": "{{jolokia_agent_url}}-MemoryLimit"
      },
      {
       "expr": "activemq_broker_MemoryPercentUsage",
       "legendFormat": "{{jolokia_agent_url}}-MemoryPercentUsage"
      }
     ]
    },
    {
     "title": "Broker Temp",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "activemq_broker_TempLimit",
       "legendFormat": "{{jolokia_agent_url}}-TempLimit"
      },
      {
       "expr": "activemq_broker_TempPercentUsage",
       "legendFormat": "{{jolokia_agent_url}}-StorePercentUsage"
      }
     ]
    }
   ]
  },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queues sizes",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
     "targets": [
      { "expr": "activemq_queue_QueueSize", "legendFormat": "{{ destinationName }}" }
     ]
    },
    {
     "title": "Queues Consumer",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
     "targets": [
      { "expr": "activemq_queue_ConsumerCount", "legendFormat": "{{destinationName}}" }
     ]
    },
    {
     "title": "Queues Dequeue",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
     "targets": [
      { "expr": "activemq_queue_DequeueCount", "legendFormat": "{{ destinationName }}" }
     ]
    },
    {
     "title": "Queues Enqueue",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
     "targets": [
      { "expr": "activemq_queue_EnqueueCount", "legendFormat": "{{ destinationName }}" }
     ]
    }
   ]
  },
  {
   "title": "Topics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Topics Size",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "targets": [
      { "expr": "activemq_topic_QueueSize", "legendFormat": "{{ destinationName }}" }
     ]
    },
    {
     "title": "Topics Consumer",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
     "targets": [
      { "expr": "activemq_topic_ConsumerCount", "legendFormat": "{{ destinationName }}" }
     ]
    },
    {
     "title": "Topics Dequeue",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
     "targets": [
      { "expr": "activemq_topic_DequeueCount", "legendFormat": "{{ destinationName }}" }
     ]
    },
    {
     "title": "Topics Enqueue",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
     "targets": [
      { "expr": "activemq_topic_EnqueueCount", "legendFormat": "{{ destinationName }}" }
     ]
    }
   ]
  }
 ]
}