{
 "title": "DotNet Server",
 "description": "Performance and health metrics for your DotNet Web Servers using Telegraf and Prometheus",
 "tags": [
  "prometheus",
  "dotnet"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Web/App Server",
    "query": "label_values(win_system_System_Up_Time, instance)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(win_system_System_Up_Time{instance=\"$server\"}, host)"
   },
   {
    "name": "apppool",
    "label": "App Pool",
    "query": "label_values(win_app_pool_Current_Application_Pool_State{instance=\"$server\"}, counterinstance)"
   }
  ]
 },
 "panels": [
  { "title": "Web Server Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Web Sites",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count (sum by (counterinstance) (win_websvc_Current_Connections{instance=\"$server\"}))"
    }
   ]
  },
  {
   "title": "App Pools",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (sum by (counterinstance) (win_app_pool_Current_Application_Pool_State{instance=\"$server\"}))"
    }
   ]
  },
  {
   "title": "App Pools Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (sum by (counterinstance) (win_app_pool_Current_Application_Pool_State{instance=\"$server\"} == 3)) / count (sum by (counterinstance) (win_app_pool_Current_Application_Pool_State{instance=\"$server\"}))"
    }
   ]
  },
  {
   "title": "Requests/Sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(win_aspnet_app_Requests_persec{instance=\"$server\"})",
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "Exceps/Sec",
   "type": "singlestat",
   "description": "Displays the number of exceptions thrown per second.\n\nThis includes both .NET exceptions and unmanaged exceptions that are converted into .NET exceptions.",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(win_dotnet_exceptions___of_Exceps_Thrown___sec{instance=\"$server\"})",
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "Unhandled Errors",
   "type": "singlestat",
   "description": "An unhandled error is any run-time exception that is not trapped in user code and enters the ASP.NET internal error-handling logic.\n\nThis counter is reset with each recycle.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(win_aspnet_app_Errors_Unhandled_During_Execution{instance=\"$server\"})"
    }
   ]
  },
  {
   "title": "Errors Total",
   "type": "singlestat",
   "description": "The total number of errors that occur during the execution of HTTP requests, including any parser, compilation, or run-time errors.\n\nThis counter is reset with each recycle.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(win_aspnet_app_Errors_Total{instance=\"$server\"})"
    }
   ]
  },
  { "title": "Web Server Overview II", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "win_cpu_Percent_Processor_Time{instance=\"$server\", counterinstance=\"_Total\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" }
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "win_mem_Available_Bytes{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Requests Succeeded",
   "type": "singlestat",
   "description": "Status code 200",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(win_aspnet_app_Requests_Succeeded{instance=\"$server\"}) / sum(win_aspnet_app_Requests_Total{instance=\"$server\"})"
    }
   ]
  },
  {
   "title": "Req. Failed",
   "type": "singlestat",
   "description": "Any status codes greater than or equal to 400.\n\nIncludes Requests Not Found and Requests Timed Out.",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(win_aspnet_app_Requests_Failed{instance=\"$server\"})",
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(win_websvc_Current_Connections{instance=\"$server\"})",
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "Worker Process Running Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sort_desc(win_process_Elapsed_Time{instance=\"$server\"}) > 0",
     "legendFormat": "{{ counterinstance }}"
    }
   ]
  },
  {
   "title": "Process | CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "This value is calculated over the base line of (No of Logical CPUS * 100)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "win_process_Percent_Processor_Time{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process | Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Working Set",
     "type": "graph",
     "description": "Working Set refers to the total physical memory (RAM) used by the process. However, unlike private bytes, this also includes memory-mapped files and various other resources.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "win_process_Working_Set{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Private Bytes",
     "type": "graph",
     "description": "Private Bytes refer to the amount of memory that the process executable has asked for - not necessarily the amount it is actually using. They are \"private\" because they (usually) exclude memory-mapped files (i.e. shared DLLs).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "win_process_Private_Bytes{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process | Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker Process Running Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "win_process_Elapsed_Time{instance=\"$server\", counterinstance=~\"w3wp.*\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Handle Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_process_Handle_Count{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Thread Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_process_Thread_Count{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Web Service | Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "win_websvc_Bytes_Sent_persec{instance=\"$server\"}",
       "legendFormat": "Sent {{ counterinstance }}"
      },
      {
       "expr": "win_websvc_Bytes_Received_persec{instance=\"$server\"}",
       "legendFormat": "Received {{ counterinstance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Web Service | Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests/Sec - Get",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_websvc_Get_Requests_persec{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Requests/Sec - Post",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_websvc_Post_Requests_persec{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Requests/Sec - Not Found",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_websvc_Not_Found_Errors_persec{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Requests/Sec - Head",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_websvc_Head_Requests_persec{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Web Service | Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_websvc_Current_Connections{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Pool | Current State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "$apppool",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
     "repeat": "apppool",
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "win_app_pool_Current_Application_Pool_State{instance=\"$server\", counterinstance=~\"$apppool\"}"
      }
     ]
    },
    {
     "title": "$apppool",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 16 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "win_app_pool_Current_Application_Pool_State{instance=\"$server\", counterinstance=~\"$apppool\"}"
      }
     ]
    },
    {
     "title": "$apppool",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 16 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "win_app_pool_Current_Application_Pool_State{instance=\"$server\", counterinstance=~\"$apppool\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Pool | State Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Pool State",
     "type": "graph",
     "description": "1 - Uninitialized, 2 - Initialized, 3 - Running, 4 - Disabling, 5 - Disabled, 6 - Shutdown Pending, 7 - Delete Pending",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_app_pool_Current_Application_Pool_State{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Pool | Performance counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recycles",
     "type": "graph",
     "description": "The number of times that the application pool has been recycled since Windows Process Activation Service (WAS) started.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_app_pool_Total_Application_Pool_Recycles{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "graph",
     "description": "The length of time that the application pool has been running since Windows Process Activation Service (WAS) started.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "win_app_pool_Total_Application_Pool_Uptime{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Worker Process Failures",
     "type": "graph",
     "description": "The number of times that worker processes have crashed since the application pool was started.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_app_pool_Total_Worker_Process_Failures{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "ASP .NET | Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Currently Executing",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_aspnet_app_Requests_Executing{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Pipeline Instance Count",
     "type": "graph",
     "description": "The number of active request pipeline instances for the specified ASP.NET application.\n\nSince only one execution thread can run within a pipeline instance, this number gives the maximum number of concurrent requests that are being processed for a given application.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_aspnet_app_Pipeline_Instance_Count{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Request Wait Time",
     "type": "graph",
     "description": "The number of milliseconds the most recent request was waiting in the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "win_aspnet_app_Request_Wait_Time{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Requests In Application Queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_aspnet_app_Requests_in_Application_Queue{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Requests Timed Out",
     "type": "graph",
     "description": "Status code 500",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_aspnet_app_Requests_Timed_Out{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Requests Not Found",
     "type": "graph",
     "description": "Status code 404 or 414",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_aspnet_app_Requests_Not_Found{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Requests Total",
     "type": "graph",
     "description": "The total number of requests since the service was started.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_aspnet_app_Requests_Total{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Compilations Total",
     "type": "graph",
     "description": "The total number of compilations that have taken place during the lifetime of the current Web server process.\n\nCompilation occurs when a file with an .aspx, .asmx, .ascx, or .ashx file name extension, or a code-behind source file, is dynamically compiled on the server.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_aspnet_app_Compilations_Total{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Unhandled Errors During Execution",
     "type": "graph",
     "description": "The total number of unhandled errors that occur during the execution of HTTP requests.\n\nAn unhandled error is any run-time exception that is not trapped in user code and enters the ASP.NET internal error-handling logic.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_aspnet_app_Errors_Unhandled_During_Execution{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Errors Total",
     "type": "graph",
     "description": "The total number of errors that occur during the execution of HTTP requests, including any parser, compilation, or run-time errors.\n\nThis counter is the sum of the Errors During Compilation, Errors During Preprocessing, and Errors During Execution counters.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_aspnet_app_Errors_Total{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    }
   ]
  },
  {
   "title": ".NET Framework | Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "# of Exceptions Thrown/Sec",
     "type": "graph",
     "description": "Displays the number of exceptions thrown per second.\n\nThis includes both .NET exceptions and unmanaged exceptions that are converted into .NET exceptions. For example, an HRESULT returned from unmanaged code is converted to an exception in managed code.\n\nThis counter includes both handled and unhandled exceptions. It is not an average over time; it displays the difference between the values observed in the last two samples divided by the duration of the sample interval. This counter is an indicator of potential performance problems if a large (>100s) number of exceptions are thrown.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_exceptions___of_Exceps_Thrown___sec{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    }
   ]
  },
  {
   "title": ".NET Framework | Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Time In JIT",
     "type": "graph",
     "description": "Displays the percentage of elapsed time spent in JIT compilation since the last JIT compilation phase.\n\nThis counter is updated at the end of every JIT compilation phase. A JIT compilation phase occurs when a method and its dependencies are compiled.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_jit_Percent_Time_in_Jit{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Current Queue Length",
     "type": "graph",
     "description": "Displays the total number of threads that are currently waiting to acquire a managed lock in the application.\n\nThis counter is not an average over time; it displays the last observed value.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_locks_Current_Queue_Length{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Queue Length/Sec",
     "type": "graph",
     "description": "Displays the number of threads per second that are waiting to acquire a lock in the application.\n\nThis counter is not an average over time; it displays the difference between the values observed in the last two samples divided by the duration of the sample interval.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_locks_Queue_Length___sec{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Total # of Contentions",
     "type": "graph",
     "description": "Displays the total number of times that threads in the runtime have attempted to acquire a managed lock unsuccessfully.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_locks_Total___of_Contentions{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "# of current logical Threads",
     "type": "graph",
     "description": "Displays the number of current managed thread objects in the application.\n\nThis counter maintains the count of both running and stopped threads. This counter is not an average over time; it displays only the last observed value.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_locks___of_current_logical_Threads{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "# of current physical Threads",
     "type": "graph",
     "description": "Displays the number of native operating system threads created and owned by the common language runtime to act as underlying threads for managed thread objects.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_locks___of_current_physical_Threads{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    }
   ]
  },
  {
   "title": ".NET Framework | Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Time in GC",
     "type": "graph",
     "description": "Displays the percentage of elapsed time that was spent performing a garbage collection since the last garbage collection cycle.\n\nThis counter usually indicates the work done by the garbage collector to collect and compact memory on behalf of the application. This counter is updated only at the end of every garbage collection. This counter is not an average; its value reflects the last observed value.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_mem_Percent_Time_in_GC{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "# Bytes in all Heaps",
     "type": "graph",
     "description": "Displays the sum of the Gen 1 Heap Size, Gen 2 Heap Size, and Large Object Heap Size counters.\n\nThis counter indicates the current memory allocated in bytes on the garbage collection heaps.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_mem___Bytes_in_all_Heaps{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Allocated Bytes/Sec",
     "type": "graph",
     "description": "Displays the number of bytes per second allocated on the garbage collection heap.\n\nThis counter is updated at the end of every garbage collection, not at each allocation. This counter is not an average over time; it displays the difference between the values observed in the last two samples divided by the duration of the sample interval.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_mem_Allocated_Bytes_persec{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Finalization Survivors",
     "type": "graph",
     "description": "Displays the number of garbage-collected objects that survive a collection because they are waiting to be finalized.\n\nIf these objects hold references to other objects, those objects also survive but are not counted by this counter.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_mem_Finalization_Survivors{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "# of Pinned Objects",
     "type": "graph",
     "description": "Displays the number of pinned objects encountered in the last garbage collection.\n\nA pinned object is one that the garbage collector cannot move in memory.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_mem___of_Pinned_Objects{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    }
   ]
  },
  {
   "title": ".NET Framework | Security",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Time in RT checks",
     "type": "graph",
     "description": "Displays the percentage of elapsed time spent performing runtime code access security checks since the last sample.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_security_Percent_Time_in_RT_checks{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Stack Walk Depth",
     "type": "graph",
     "description": "Displays the depth of the stack during that last runtime code access security check.\n\nRuntime code access security checks are performed by walking the stack. This counter is not an average; it displays only the last observed value.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_security_Stack_Walk_Depth{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Total Runtime Checks",
     "type": "graph",
     "description": "Displays the total number of runtime code access security checks performed since the application started.\n\nRuntime code access security checks are performed when a caller demands a particular permission. The runtime check is made on every call by the caller and examines the current thread stack of the caller. When used with the Stack Walk Depth counter, this counter indicates the performance penalty that occurs for security checks.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_dotnet_security_Total_Runtime_Checks{instance=\"$server\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    }
   ]
  }
 ]
}