{
 "title": "SQL Server",
 "description": "Performance and health metrics for your SQL Servers using Telegraf and Prometheus",
 "tags": [
  "prometheus",
  "telegraf",
  "sqlserver"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "DB Instance",
    "query": "label_values(sqlserver_performance, sql_instance)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(sqlserver_performance{sql_instance = \"$instance\"}, host)"
   }
  ]
 },
 "panels": [
  { "title": "Database overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hostname",
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "content": "<p style=\"text-align: center; font-size: 140%; font-weight: bold\">\n  $host\n</p>"
  },
  {
   "title": "Databases",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum({ __name__ =~ \"sqlserver_server_properties_db_.*\", sql_instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "ONLINE",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sqlserver_server_properties_db_online{sql_instance=\"$instance\"}) / sum({ __name__ =~ \"sqlserver_server_properties_db_.*\", sql_instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "OFFLINE",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_offline{sql_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "RECOVERING",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_recovering{sql_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "PENDING",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_recoveryPending{sql_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "RESTORING",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_restoring{sql_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "SUSPECT",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_suspect{sql_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Target Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Target Server Memory (KB)\", sql_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Used memory (KB)\", sql_instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Disk Reads (bytes/sec)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(sqlserver_performance{counter=\"Disk Read Bytes/sec\", sql_instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Disk Writes (bytes/sec)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(sqlserver_performance{counter=\"Disk Write Bytes/sec\", sql_instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Full scans per sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(sqlserver_performance{counter=\"Full Scans/sec\", sql_instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Index searches per sec",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(sqlserver_performance{counter=\"Index Searches/sec\", sql_instance=\"$instance\"}[1m])"
    }
   ]
  },
  { "title": "Performance counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "SQL Server Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sqlserver_performance{counter=\"Batch Requests/sec\", sql_instance=\"$instance\"}[1m])",
     "legendFormat": "Batch Requests/sec"
    },
    {
     "expr": "sqlserver_performance{counter=\"User Connections\", sql_instance=\"$instance\"}",
     "legendFormat": "User Connections"
    },
    {
     "expr": "rate(sqlserver_performance{counter=\"Logins/sec\", sql_instance=\"$instance\"}[1m])",
     "legendFormat": "Logins/sec"
    },
    {
     "expr": "rate(sqlserver_performance{counter=\"Logouts/sec\", sql_instance=\"$instance\"}[1m])",
     "legendFormat": "Logouts/sec"
    },
    {
     "expr": "rate(sqlserver_performance{counter=\"SQL Compilations/sec\", sql_instance=\"$instance\"}[1m])",
     "legendFormat": "SQL Compilations/sec"
    },
    {
     "expr": "rate(sqlserver_performance{counter=\"SQL Re-Compilations/sec\", sql_instance=\"$instance\"}[1m])",
     "legendFormat": "SQL Re-Compilations/sec"
    },
    {
     "expr": "sqlserver_performance{counter=\"Blocked tasks\", sql_instance=\"$instance\"}",
     "legendFormat": "Blocked tasks"
    }
   ]
  },
  {
   "title": "Databases Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Transactions/sec",
     "expr": "rate(sqlserver_performance{counter=\"Transactions/sec\", counterinstance=\"Total\", sql_instance=\"$instance\"}[1m])",
     "legendFormat": "Transactions/sec"
    },
    {
     "alias": "Write Transactions/sec",
     "expr": "rate(sqlserver_performance{counter=\"Write Transactions/sec\", counterinstance=\"Total\", sql_instance=\"$instance\"}[1m])",
     "legendFormat": "Write Transactions/sec"
    },
    {
     "alias": "Log Flushes/sec",
     "expr": "rate(sqlserver_performance{counter=\"Log Flushes/sec\", counterinstance=\"Total\", sql_instance=\"$instance\"}[1m])",
     "legendFormat": "Log Flushes/sec"
    },
    {
     "alias": "Lock Timeouts/sec",
     "expr": "rate(sqlserver_performance{counter=\"Lock Timeouts/sec\", counterinstance=\"Total\", sql_instance=\"$instance\"}[1m])",
     "legendFormat": "Lock Timeouts/sec"
    },
    {
     "alias": "Number of Deadlocks/sec",
     "expr": "rate(sqlserver_performance{counter=\"Number of Deadlocks/sec\", counterinstance=\"Total\", sql_instance=\"$instance\"}[1m])",
     "legendFormat": "Number of Deadlocks/sec"
    },
    {
     "alias": "Lock Waits/sec",
     "expr": "rate(sqlserver_performance{counter=\"Lock Waits/sec\", counterinstance=\"Total\", sql_instance=\"$instance\"}[1m])",
     "legendFormat": "Lock Waits/sec"
    },
    {
     "alias": "Latch Waits/sec",
     "expr": "rate(sqlserver_performance{counter=\"Latch Waits/sec\", sql_instance=\"$instance\"}[1m])",
     "legendFormat": "Latch Waits/sec"
    }
   ]
  },
  {
   "title": "Waits Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wait Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(sqlserver_waitstats_wait_time_ms{sql_instance=\"$instance\"}[1m])",
       "legendFormat": "{{ wait_category }} - {{ wait_type}}"
      }
     ]
    },
    {
     "title": "Wait Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(sqlserver_waitstats_waiting_tasks_count{sql_instance=\"$instance\"}[1m])",
       "legendFormat": "{{ wait_category }} - {{ wait_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database | Data Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "expr": "sqlserver_performance{counter=\"Data File(s) Size (KB)\", sql_instance=\"$instance\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    },
    {
     "title": "Database | Log Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "expr": "sqlserver_performance{counter=\"Log File(s) Size (KB)\", sql_instance=\"$instance\"}",
       "legendFormat": "{{ counterinstance }}"
      }
     ]
    }
   ]
  }
 ]
}