groups:
  - name: recording_rules
    interval: 5s
    rules:
      - record: node_exporter:node_filesystem_free:fs_used_percents
        expr: 100 - 100 * ( node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} )

      - record: node_exporter:node_memory_available:memory_used_percents
        expr: 100 - 100 * (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)

  - name: alerting_rules
    rules:

      - alert: SystemDown
        expr: up == 0
        labels:
          severity: Critical
        annotations:
          description: Instance is down.

      - alert: MySQLDown
        expr: mysql_up == 0
        labels:
          severity: Critical
        annotations:
          description: MySQL is down.

      - alert: MemoryAvailable10%
        expr: node_exporter:node_memory_available:memory_used_percents >= 90
        for: 5m
        labels:
          severity: Critical
        annotations:
          summary: "Instance {{ $labels.instance }} high memory usage"
          description: "{{ $labels.instance }} has more than 90% of its memory used."

      - alert: DiskSpace10%Free
        expr: node_exporter:node_filesystem_free:fs_used_percents >= 90
        labels:
          severity: Warning
        annotations:
          summary: "Instance {{ $labels.instance }} is low on disk space"
          description: "{{ $labels.instance }} has only {{ $value }}% free."
